### ISSUE TITLE
Minor issue in Prosody on Uberspace description

### ISSUE THREAD

**Issue by momu** [alexh-name/0101010.one#8]
Hi, 
in my case
`ll "${HOME}"/etc/prosody/prosody.cfg.lua.stock`
returns
`-r--r--r--. 1 user user 7830  6. Feb 12:24 /home/user/etc/prosody/prosody.cfg.lua.stock`

using your proposed commands for updating it fails when doing
`cp "${HOME}"/.toast/armed/etc/prosody/prosody.cfg.lua "${HOME}"/etc/prosody/prosody.cfg.lua.stock`

so adding
`&& chmod u+w "${HOME}"/etc/prosody/prosody.cfg.lua.stock \`
before copying should do it.

Thanks a lot for this manual ;)

**Comment by alexh-name** [comment]
You're welcome!
Thanks for pointing it out!
af24b5d51081cf12824109276dfcded289e3be22
